package com.gever.goa.user.dao.impl;

import com.gever.goa.user.dao.UserFactory;
import com.gever.goa.user.dao.UserDao;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: TUser ??</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company:${config.company}</p>
 * @Author:		${config.author}
 * @Version:${config.version}
 *
 */
public class DefaultUserFactory extends UserFactory{
    public DefaultUserFactory() {
    }
    /**
     * @param dbData datasource
     * @return UserDAO instance
     */
     public UserDao createUserDAO(String dbData){
         return new UserDaoImpl(dbData);
     }
}