package com.gever.goa.book.dao;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: Book 实体</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company:OSMatrix 天行软件</p>
 * @Author:		HuHJ
 * @Version:1.0
 *
 */
public abstract class BookFactory {
    private static String className = "com.gever.goa.book.dao.impl.DefaultBookFactory";
    private static BookFactory factory = null;
    public BookFactory() {
    }

    /**
    */
   public static synchronized BookFactory getInstance() {
       if (factory == null) {
           try {
               Class c = Class.forName(className);
               factory = (BookFactory) c.newInstance();
           } catch (Exception e) {
               System.err.println("Failed to load BookFactory class " +
                   className);
               e.printStackTrace();

               return null;
           }
       }

       return factory;
   }
   public abstract BookDao createBookDAO(String dbData);


}