package com.gever.goa.user.vo;

import java.util.*;
import com.gever.vo.BaseVO;
import com.gever.vo.VOInterface;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: TUser ??</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: ${config.company}</p>
 * @Author:		 ${config.author}
 * @Version: ${config.version}
 *
 */ 
public class UserVO extends BaseVO implements VOInterface {
   public UserVO(){ }
    
   private java.lang.String id;		 	//id
   private java.lang.String name;		 	//name
   private java.lang.String email;		 	//email

   public java.lang.String getId() { return this.id;   
   }
   public void setId(java.lang.String id) {this.id = id;   
   }
   public java.lang.String getName() { return this.name;   
   }
   public void setName(java.lang.String name) {this.name = name;   
   }
   public java.lang.String getEmail() { return this.email;   
   }
   public void setEmail(java.lang.String email) {this.email = email;   
   }

   private static final int id_col = 1 - 1; // ID
   private static final int name_col = 2 - 1; // ID
   private static final int email_col = 3 - 1; // ID

    public String getValue(String name) 
    {
				if("id".equalsIgnoreCase(name) == true) {
             return  this.id;
         }
				if("name".equalsIgnoreCase(name) == true) {
             return  this.name;
         }
				if("email".equalsIgnoreCase(name) == true) {
             return  this.email;
         }
	        return "";
	    }
	    
    public void setValue(String name, String value) 
    {
    if("id".equalsIgnoreCase(name) == true) {
             this.id = value;
         }
		    if("name".equalsIgnoreCase(name) == true) {
             this.name = value;
         }
		    if("email".equalsIgnoreCase(name) == true) {
             this.email = value;
         }
			         return;
	    }

    public String getColType(String name) {
        String colType = new String();
		    	    if("id".equalsIgnoreCase(name) == true) {
             colType = "INT(11)";
         }
		    	    if("name".equalsIgnoreCase(name) == true) {
             colType = "VARCHAR(20)";
         }
		    	    if("email".equalsIgnoreCase(name) == true) {
             colType = "VARCHAR(20)";
         }
        return colType;
    }
    
    public String getTableName() { return "qiqu_user"; 	     }
    public String getPkFields()  { return "id,";    }
    public String getModifyFields() {
    	    String fields="";
		        	fields = fields + "name,";
	        	fields = fields + "email,";
        return fields;
    }
    public String getAllFields() {
    	    String fields="";
        fields = fields + "id,";
        fields = fields + "name,";
        fields = fields + "email,";
        return fields;
    }
    public void setValues(String[] values) {
		this.id = values[id_col];
		this.name = values[name_col];
		this.email = values[email_col];
    }

    public void setOtherProperty(String[] values) {
    }
}