/*
SQLyog - Free MySQL GUI v5.15
Host - 5.0.22-community-nt : Database - cop
*********************************************************************
Server version : 5.0.22-community-nt
*/

SET NAMES utf8;

SET SQL_MODE='';
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

/*Data for the table `is_dotype` */

insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('BZMB',1,NULL,7,'标准模板');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('CWZX',1,NULL,6,'财务中心');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('DFFG',1,NULL,1,'地方法规');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('GG',1,NULL,2,'公告');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('GJFG',1,NULL,1,'国家法规');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('GXWZ',1,NULL,7,'共享文章');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('HYXW',1,NULL,5,'行业新闻');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('JKXX',1,NULL,0,'健康信息');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('JXZL',1,NULL,7,'技术资料');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('JXZX',1,NULL,6,'技术中心');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('LYXX',1,NULL,0,'旅游信息');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('NX',2,'PXZL',7,'内训');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('PXZL',1,NULL,7,'培训资料');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('QTPX',2,'PXZL',7,'其他培训');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('QYWH',1,NULL,7,'企业文化');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('RJKF',2,'PXZL',7,'软件开发');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('RJXX',1,NULL,0,'软件信息');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('RLZY',2,'XZZX',6,'人力资源管理');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('TZ',1,NULL,2,'通知');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('XWXX',1,NULL,0,'新闻信息');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('XZGL',2,'XZZX',6,'行政管理');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('XZZX',1,NULL,6,'行政中心');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('YDXX',1,NULL,0,'运动休闲');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('YXFWZX',1,NULL,6,'运行服务中心');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('YXZX',1,NULL,6,'营销中心');
insert into `is_dotype` (`INFO_TYPE`,`TYPELEVEL`,`PARENT_TYPE`,`MODULEFLAG`,`REMARK`) values ('ZCFG',1,NULL,1,'政策法规');

/*Data for the table `is_standard_model` */

insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126134848190',3,'2005-04-15',1,'月汇报',1,'/cell/template/monthsum_template.cll','gdca_month_report.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126135317133',4,'2005-04-15',1,'年汇报',1,'/cell/template/yearsum_template.cll','gdca_year_report.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126135350157',6,'2005-04-15',1,'月度目标',1,'/cell/template/monthtarget_template.cll','monthtarget_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126135450162',9,'2005-04-15',1,'年度总结',1,'/cell/template/yearsum_template.cll','yearsum_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126135506143',10,'2005-04-15',1,'五年规划',1,'/cell/template/fiveyearlayout_template.cll','fiveyearlayout_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126135521158',11,'2005-04-15',1,'工作汇报',1,'/cell/template/workreport.cll','workreport.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041126135540147',12,'2005-04-15',1,'授权书',1,'/cell/template/impower.cll','impower.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041128190036104121',7,'2005-04-15',1,'月度总结',1041,'/cell/template/monthsum_template.cll','yearsum_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041128190050104142',8,'2005-04-15',1,'年度目标',1041,'/cell/template/yeartarget_template.cll','yeartarget_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041203162507131',5,'2005-04-15',1,'每周目标',1,'/cell/template/weektarget_template.cll','weektarget_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20041209175237157',2,'2005-04-15',1,'周汇报',1,'/cell/template/weeksum_template.cll','workreport.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20050415125633158',1,'2005-04-15',1,'工作日志',1,'/cell/template/worklog_template.cll','worklog_template.cll',NULL,NULL,0,NULL);
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20060720192045138',16,'2006-07-20',0,'news测试',1,'/uploadfiles/template/200607201920451240/1153394445243.cll','news.cll',NULL,NULL,0,'GG');
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20060720193939188',13,'2006-07-20',1,'news',1,'/uploadfiles/template/200607201939391550/1153395579443.cll','news.cll',NULL,NULL,0,'TZ');
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20060721144936121',13,'2006-07-21',0,'放假通知',1,'uploadfiles\\20060721144936185.html','20060721144936185.html',NULL,NULL,1,'GG');
insert into `is_standard_model` (`MODEL_CODE`,`MODEL_TYPE`,`CREATE_DATE`,`ISSUE_FLAG`,`MODEL_NAME`,`USER_CODE`,`FILE_PATH`,`FILE_NAME`,`WORD_CONTENT`,`CONTENT`,`EDITOR_TYPE`,`INFO_TYPE`) values ('20060721150833125',13,'2006-07-21',1,'中奖名单',1,'/uploadfiles/template/200607211508331700/1153465713607.cll','is_GSDT_GG.cll',NULL,NULL,0,'GG');

/*Data for the table `sys_duty` */

insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0002','董事',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0003','总经理',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0004','副总经理',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0005','总经理助理',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0006','行政总监',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0007','主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0008','职员',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0009','高级销售代表',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0010','区域销售主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0011','行业销售主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0012','营销副总监',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0013','业务管理主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0014','业务管理专员',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0015','市场拓展主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0018','售前工程师',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0019','研发部经理',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0020','研发工程师',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0021','工程服务主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0022','运行管理经理',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0023','运行管理专员',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0024','客户服务主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0025','客服专员',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0026','主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0027','证书操作员',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0028','证书管理员',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0029','运维工程师',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0030','财务主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0031','出纳',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0032','司机',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0033','行政主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0034','人力资源主管',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0035','前台',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('0036','销售代表',NULL);
insert into `sys_duty` (`DUTY_CODE`,`DUTY_NAME`,`REMARKS`) values ('1','董事长',NULL);

/*Data for the table `sys_job` */

insert into `sys_job` (`JOB_CODE`,`JOB_NAME`,`REMARKS`) values ('GCS','工程师','工程师');

/*Data for the table `sys_knowledge` */

/*Data for the table `sys_marriage` */

insert into `sys_marriage` (`MARRIAGE_CODE`,`MARRIAGE`,`REMARKS`) values ('1','未婚',NULL);
insert into `sys_marriage` (`MARRIAGE_CODE`,`MARRIAGE`,`REMARKS`) values ('2','已婚',NULL);
insert into `sys_marriage` (`MARRIAGE_CODE`,`MARRIAGE`,`REMARKS`) values ('3','丧偶',NULL);
insert into `sys_marriage` (`MARRIAGE_CODE`,`MARRIAGE`,`REMARKS`) values ('4','离婚',NULL);
insert into `sys_marriage` (`MARRIAGE_CODE`,`MARRIAGE`,`REMARKS`) values ('99','其他',NULL);

/*Data for the table `sys_national` */

insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('1','汉族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('10','朝鲜族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('11','满族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('12','侗族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('13','瑶族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('14','白族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('15','土家族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('16','哈尼族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('17','哈萨克族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('18','傣族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('19','黎族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('2','蒙古族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('20','傈僳族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('21','佤族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('22','畲族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('23','高山族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('24','拉祜族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('25','水族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('26','东乡族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('27','纳西族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('28','景颇族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('29','柯尔克孜族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('3','回族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('30','土族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('31','达斡尔族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('32','仫佬族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('33','羌族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('34','布朗族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('35','撒拉族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('36','毛南族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('37','仡佬族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('38','锡伯族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('39','阿昌族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('4','藏族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('40','普米族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('41','塔吉克族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('42','怒族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('43','乌孜别克族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('44','俄罗斯族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('45','鄂温克族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('46','德昂族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('47','保安族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('48','裕固族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('49','京族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('5','维吾尔族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('50','塔塔尔族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('51','独龙族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('52','鄂伦春族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('53','赫哲族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('54','门巴族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('55','珞巴族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('56','基诺族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('6','苗族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('7','彝族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('8','壮族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('9','布依族',NULL);
insert into `sys_national` (`NATIONAL_CODE`,`NATIONAL_NAME`,`REMARKS`) values ('91','待识别',NULL);

/*Data for the table `sys_polity` */

insert into `sys_polity` (`POLITY_CODE`,`POLITY_NAME`,`REMARKS`) values ('02','预备党员',NULL);
insert into `sys_polity` (`POLITY_CODE`,`POLITY_NAME`,`REMARKS`) values ('03','团员',NULL);
insert into `sys_polity` (`POLITY_CODE`,`POLITY_NAME`,`REMARKS`) values ('13','群众',NULL);
insert into `sys_polity` (`POLITY_CODE`,`POLITY_NAME`,`REMARKS`) values ('34','43','43');
insert into `sys_polity` (`POLITY_CODE`,`POLITY_NAME`,`REMARKS`) values ('434','43','34');

/*Data for the table `sys_sex` */

insert into `sys_sex` (`SEX_CODE`,`SEX_NAME`,`REMARKS`) values ('1','男',NULL);
insert into `sys_sex` (`SEX_CODE`,`SEX_NAME`,`REMARKS`) values ('2','女',NULL);
insert into `sys_sex` (`SEX_CODE`,`SEX_NAME`,`REMARKS`) values ('9','未说明的性别',NULL);

/*Data for the table `sys_unit_info` */

insert into `sys_unit_info` (`UNIT_CODE`,`UNIT_NAME`,`PHONE`,`FAX`,`E_MAIL`,`HOME_PAGE`,`REMARK`,`UNIT_TYPE`) values ('天行软件','天行软件技术有限公司','','','huhj2008@126.com','','Selenium test',0);

/*Data for the table `t_resoperation` */

insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (1,'操作','包括新增、修改、删除部门及设置部门的岗位和人员等功能。',8011,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (2,'浏览','仅仅只能查看部门的结构和信息。',8011,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (3,'操作','包括新增、修改、删除岗位及设置岗位的人员等功能。',8012,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (4,'浏览','仅仅只能查看岗位信息。',8012,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (5,'操作','包括设置部门的人员和为人员设置岗位等功能。',8013,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (6,'浏览','包括查看人员信息和对人员进行查询等功能。',8013,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (7,'操作','包括新增、修改、删除用户及设置用户的权限和角色等功能。',8021,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (8,'浏览','包括查看用户信息和对用户进行查询等功能。',8021,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (9,'操作','包括新增、修改、删除角色及设置角色的权限等功能。',8022,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (10,'浏览','仅仅只能查看角色信息。',8022,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (11,'操作','包括新增、修改、删除资源操作等功能。',8023,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (12,'浏览','仅仅只能查看操作信息。',8023,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (13,'操作','包括新增、修改、删除资源等功能。',8024,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (14,'浏览','仅仅只能查看资源信息。',8024,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (15,'操作','包括本模块的操作功能。',7015,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (16,'操作','包括导出和删除操作日志信息等功能。',8030,'ALL',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (17,'浏览','包括查询和浏览操作日志信息等功能。',8030,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (18,'操作','包括日常办公操作权限',10,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (19,'浏览','包括日常办公浏览权限',10,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (20,'操作','包括日志管理操作权限',1010,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (21,'浏览','包括日志管理浏览权限',1010,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (22,'操作','包括我的日志操作权限',1011,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (23,'浏览','包括我的日志浏览权限',1011,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (24,'操作','包括日志查询操作权限',1012,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (25,'浏览','包括日志查询浏览权限',1012,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (26,'操作','包括人周目标操作权限',1031,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (27,'浏览','包括人周目标浏览权限',1031,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (28,'操作','包括人月目标操作权限',1032,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (29,'浏览','包括人月目标浏览权限',1032,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (30,'操作','包括人年目标操作权限',1033,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (31,'浏览','包括人年目标浏览权限',1033,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (32,'操作','包括目标管理操作权限',1020,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (33,'浏览','包括目标管理浏览权限',1020,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (34,'操作','包括每周目标操作权限',1021,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (35,'浏览','包括每周目标浏览权限',1021,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (36,'操作','包括月度目标操作权限',1022,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (37,'浏览','包括月度目标浏览权限',1022,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (38,'操作','包括月度总结操作权限',1023,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (39,'浏览','包括月度总结浏览权限',1023,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (40,'操作','包括年度目标操作权限',1024,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (41,'浏览','包括年度目标浏览权限',1024,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (42,'操作','包括年度总结操作权限',1025,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (43,'浏览','包括年度总结浏览权限',1025,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (44,'操作','包括五年规划操作权限',1026,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (45,'浏览','包括五年规划浏览权限',1026,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (46,'操作','包括日程安排操作权限',1040,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (47,'浏览','包括日程安排浏览权限',1040,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (48,'操作','包括工作汇报操作权限',1030,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (49,'浏览','包括工作汇报浏览权限',1030,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (50,'操作','包括授权管理操作权限',1050,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (51,'浏览','包括授权管理浏览权限',1050,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (110,'操作','包括常用工具操作权限',70,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (111,'浏览','包括常用工具浏览权限',70,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (112,'操作','包括邮件管理操作权限',7010,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (113,'浏览','包括邮件管理浏览权限',7010,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (116,'操作','包括内部短信操作权限',7012,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (117,'浏览','包括内部短信浏览权限',7012,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (118,'操作','包括备忘录操作权限',7013,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (119,'浏览','包括备忘录浏览权限',7013,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (120,'操作','包括名片夹操作权限',7014,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (121,'浏览','包括名片夹浏览权限',7014,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (122,'操作','包括菜单定制操作权限',7015,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (123,'浏览','包括菜单定制浏览权限',7015,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (124,'操作','包括万年日历操作权限',7016,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (125,'浏览','包括万年日历浏览权限',7016,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (128,'操作','包括在线交流操作权限',9210,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (129,'浏览','包括在线交流浏览权限',9210,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (130,'操作','包括基础数据操作权限',8040,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (131,'浏览','包括基础数据浏览权限',8040,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (132,'操作','包括单位信息操作权限',8041,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (133,'浏览','包括单位信息浏览权限',8041,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (134,'操作','包括政治面貌操作权限',8042,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (135,'浏览','包括政治面貌浏览权限',8042,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (136,'操作','包括职称维护操作权限',8043,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (137,'浏览','包括职称维护浏览权限',8043,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (138,'操作','包括职务维护操作权限',8044,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (139,'浏览','包括职务维护浏览权限',8044,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (140,'操作','包括学历维护操作权限',8045,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (141,'浏览','包括学历维护浏览权限',8045,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (142,'操作','包括民族维护操作权限',8046,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (143,'浏览','包括民族维护浏览权限',8046,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (144,'操作','包括婚姻信息操作权限',8047,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (145,'浏览','包括婚姻信息浏览权限',8047,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (146,'操作','包括性别维护操作权限',8048,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (147,'浏览','包括性别维护浏览权限',8048,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (148,'操作','包括论坛管理操作权限',8050,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (149,'浏览','包括论坛管理浏览权限',8050,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (150,'操作','包括论坛维护操作权限',8051,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (151,'浏览','包括论坛维护浏览权限',8051,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (152,'操作','包括人员管理操作权限',8052,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (153,'浏览','包括人员管理浏览权限',8052,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (156,'操作','包括邮箱管理操作权限',8070,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (157,'浏览','包括邮箱管理浏览权限',8070,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (160,'操作','包括信息中心操作权限',90,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (161,'浏览','包括信息中心浏览权限',90,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (162,'操作','包括组织信息操作权限',9030,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (163,'浏览','包括组织信息浏览权限',9030,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (166,'操作','包括资源共享操作权限',9080,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (167,'浏览','包括资源共享浏览权限',9080,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (168,'操作','包括政策法规操作权限',9010,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (169,'浏览','包括政策法规浏览权限',9010,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (170,'操作','包括标准模板操作权限',9150,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (171,'浏览','包括标准模板浏览权限',9150,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (176,'操作','包括信息设置操作权限',9090,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (177,'浏览','包括信息设置浏览权限',9090,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (178,'操作','包括类型设置操作权限',9091,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (179,'浏览','包括类型设置浏览权限',9091,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (180,'操作','包括群组设置操作权限',9092,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (181,'浏览','包括群组设置浏览权限',9092,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (201,'公共操作','包括名片夹公共目录操作权限',7014,'PUBOPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (230,'操作','行业新闻操作权限',9020,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (231,'浏览','行业新闻浏览权限',9020,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (232,'操作','管理制度操作权限',9040,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (233,'浏览','管理制度浏览权限',9040,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (234,'操作','文档资料操作权限',9060,'OPT',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (235,'浏览','文档资料浏览权限',9060,'VIEW',0);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (318,'所有','操作映射',214,'ALL',NULL);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (328,'所有','行政级别',219,'ALL',NULL);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (329,'浏览','行政级别',219,'VIEW',NULL);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (330,'资源排序','资源管理',8024,'ZYPX',NULL);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (331,'部门排序','组织管理之部门排序',8011,'BMPX',NULL);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (332,'所有','数据维护',220,'ALL',NULL);
insert into `t_resoperation` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCE_ID`,`CODE`,`ORDERID`) values (1000,'公共操作','包括公共群组操作权限',9092,'PUBOPT',0);

/*Data for the table `t_resource` */

insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (0,'办公平台','GDCA办公自动化平台',NULL,NULL,-1,'3','GDP-ROOT',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (10,'日常办公','日常办公','0',NULL,0,'0','LZBG',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (70,'常用工具','常用工具','0',NULL,0,'0','tool',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (80,'信息中心','信息中心','0',NULL,0,'0','XXFW',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (90,'系统管理','系统管理','link',NULL,0,'0','GDP-XTGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (214,'操作映射','操作映射','link','/privilege/permissionMapAction.do?action=list',8020,'0','GDP-CZYS',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (219,'行政级别','行政级别','link','/privilege/levelAction.do?action=list',8010,'0','GDP-XZJB',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (220,'数据维护','资源、操作数据的导出备份','0','/basedata/BaseDataAction.do?action=toExport',90,'0','GDP-JCSJ',8);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1000,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1010,'日志管理','日志管理','0',NULL,10,'0','LZGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1011,'我的日志','我的日志','0','/dailyoffice/worklog/listworklog.do',1010,'0','WDLZ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1012,'日志查询','日志查询','0','/dailyoffice/worklog/frameteamworklog.jsp',1010,'0','LZCS',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1015,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1020,'目标管理','目标管理','0',NULL,10,'0','MBGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1021,'每周目标','每周目标','0','/dailyoffice/targetmng/frameweektarget.jsp',1020,'0','MZMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1022,'月度目标','月度目标','0','/dailyoffice/targetmng/framemonthtarget.jsp',1020,'0','YDMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1023,'月度总结','月度总结','0','/dailyoffice/targetmng/framemonthsum.jsp',1020,'0','YDZJ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1024,'年度目标','年度目标','0','/dailyoffice/targetmng/listyeartarget.do',1020,'0','NDMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1025,'年度总结','年度总结','0','/dailyoffice/targetmng/listyearsum.do',1020,'0','NDZJ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1026,'五年规划','五年规划','0','/dailyoffice/targetmng/listfiveyearlayout.do',1020,'0','WRJF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1030,'工作汇报','工作汇报','0',NULL,10,'0','GZHB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1031,'周汇报','周汇报','0','/dailyoffice/worklog/framepersonweektarget.jsp',1030,'0','LZMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1032,'月汇报','月汇报','0','/dailyoffice/worklog/framepersonmonthtarget.jsp',1030,'0','LYMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1033,'年汇报','年','0','/dailyoffice/worklog/framepersonyeartarget.jsp',1030,'0','LNMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1040,'日程安排','日程安排','0','/dailyoffice/calendararrange/listcalendarbyweek.do',10,'0','LTAP',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1045,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1050,'授权管理','授权管理','0','/dailyoffice/impowermgr/listimpower.do',10,'0','SQGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1060,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1075,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1090,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1105,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1120,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1135,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1150,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1165,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1180,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1195,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1210,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1225,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1240,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1255,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1270,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1285,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1300,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1315,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1330,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1345,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1360,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1375,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1390,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1405,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1420,'java',NULL,NULL,NULL,0,'\0','null',NULL);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1780,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1795,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1810,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1825,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1840,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1855,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1870,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1885,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1900,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1915,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1930,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1945,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1960,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1975,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (1990,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2005,'java',NULL,NULL,NULL,0,'\0','null',10);

insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2020,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2035,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2050,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2065,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2095,'java',NULL,NULL,NULL,0,'\0','null',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (2110,'java',NULL,NULL,NULL,0,'\0','null',10);

insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (7010,'邮件管理','邮件管理','0','/dailyoffice/mailmgr/mailframe.jsp',70,'0','YJGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (7012,'内部短信','内部短信','0','/dailyoffice/message/framemessage.jsp',70,'0','RBDX',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (7013,'备忘录','备忘录','0','/dailyoffice/tools/ticklerframe.jsp',70,'0','BWL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (7014,'名片夹','名片夹','0','/dailyoffice/tools/cardframe.jsp',70,'0','MBJ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (7015,'菜单定制','菜单定制','link','/jsp/menusetup/frame.jsp',70,'0','GDP-CDDZ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (7016,'万年日历','万年日历','0','/dailyoffice/tools/wannianli.html',70,'3','WNLL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8010,'组织管理','组织管理','link',NULL,90,'0','GDP-ZZGL',0);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8011,'部门管理','部门管理','link','/jsp/organization/department/department-main.jsp',8010,'0','GDP-BMGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8012,'岗位管理','岗位管理','link','/jsp/organization/job/job-main.jsp',8010,'0','GDP-GWGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8013,'人员管理','人员管理','link','/jsp/organization/employee/employee-main.jsp',8010,'0','GDP-RYGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8020,'权限管理','权限管理','link',NULL,90,'0','GDP-QXGL',1);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8021,'用户管理','用户管理','link','/privilege/userAction.do?action=list',8020,'0','GDP-YHGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8022,'角色管理','角色管理','link','/privilege/roleAction.do?action=list',8020,'0','GDP-JSGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8023,'操作管理','操作管理','link','/jsp/privilege/opt/opt-main.jsp',8020,'0','GDP-CZGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8024,'资源管理','资源管理','link','/jsp/privilege/resource/res-main.jsp',8020,'0','GDP-ZYGL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8030,'操作日志','操作日志','link','/log/loglist.do?action=list',90,'0','GDP-CZRZ',9);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8040,'基础数据','基础数据','0',NULL,90,'0','GCSJ',5);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8041,'单位信息','单位信息','0','/admin/listunit.do',8040,'0','DWXX',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8042,'政治面貌','政治面貌','0','/admin/listpolity.do',8040,'0','ZZMM',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8043,'职称维护','职称维护','0','/admin/listjob.do',8040,'0','ZCWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8044,'职务维护','职务维护','0','/admin/listduty.do',8040,'0','ZWWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8045,'学历维护','学历维护','0','/admin/listknow.do',8040,'0','XLWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8046,'民族维护','民族维护','0','/admin/listnation.do',8040,'0','MZWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8047,'婚姻信息','婚姻信息','0','/admin/listmarr.do',8040,'0','FYXX',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8048,'性别维护','性别维护','0','/admin/listsex.do',8040,'0','XBWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8050,'论坛管理','论坛管理','0',NULL,90,'0','LTGL',3);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8051,'论坛维护','论坛维护','0','/dailyoffice/bbs/mng/topboard.do',8050,'0','LTWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8052,'人员管理','人员管理','0','/dailyoffice/bbs/mng/bbsuser.do',8050,'0','LYWF',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (8070,'邮箱管理','邮箱管理','0','/dailyoffice/mailmgr/mailboxmgr/mailboxframe.jsp',90,'0','YSGL',2);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9010,'政策法规','政策法规','0','/infoservice/lawframe.jsp',80,'0','ZCFG',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9020,'行业新闻','行业新闻','0','/infoservice/tradenewsframe.jsp',80,'0','HYXW',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9030,'公司动态','公司动态','0','/infoservice/orginfoframe.jsp',80,'0','ZZXX',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9040,'管理制度','管理制度','0','/infoservice/managesystemframe.jsp',80,'0','GLZD',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9060,'文档资料','文档资料','0','/infoservice/docinfoframe.jsp',80,'0','WDZL',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9080,'资源共享','资源共享','0','/infoservice/publicinfoframe.jsp',80,'0','GGXX',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9090,'信息设置','信息设置','0',NULL,80,'0','XXSZ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9091,'类型设置','类型设置','0','/infoservice/typeframe.jsp',9090,'0','LSSZ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9092,'群组设置','群组设置','0','/infoservice/groupframe.jsp',9090,'0','ZQSZ',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9150,'模板设置','模板设置','0','/infoservice/templateframe.jsp',80,'0','BZMB',10);
insert into `t_resource` (`ID`,`NAME`,`DESCRIPTION`,`RESOURCETYPE`,`LINK`,`PARENT_ID`,`TARGET`,`CODE`,`ORDERID`) values (9210,'BBS论坛','BBS论坛','0','/dailyoffice/bbs/main.do',70,'0','ZXJL',10);

select * from `t_resource`;

SET SQL_MODE=@OLD_SQL_MODE;