package com.gever.goa.user.dao;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: TUser ??</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company:${config.company}</p>
 * @Author:		${config.author}
 * @Version:${config.version}
 *
 */
public abstract class UserFactory {
    private static String className = "com.gever.goa.user.dao.impl.DefaultUserFactory";
    private static UserFactory factory = null;
    public UserFactory() {
    }

    /**
    */
   public static synchronized UserFactory getInstance() {
       if (factory == null) {
           try {
               Class c = Class.forName(className);
               factory = (UserFactory) c.newInstance();
           } catch (Exception e) {
               System.err.println("Failed to load UserFactory class " +
                   className);
               e.printStackTrace();

               return null;
           }
       }

       return factory;
   }
   public abstract UserDao createUserDAO(String dbData);


}