package com.gever.goa.user.action;

import com.gever.struts.form.BaseForm;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: TUser ??</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: ${config.company}</p>
 * @Author:		 ${config.author}
 * @Version: ${config.version}
 *
 */
public class UserForm extends BaseForm{
    public UserForm() {}

}