package com.gever.goa.book.action;

import com.gever.goa.base.BaseForm;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: Book 实体</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company:OSMatrix 天行软件</p>
 * @Author:		HuHJ
 * @Version:1.0
 *
 */
public class BookForm extends BaseForm{
    public BookForm() {}

}