package  com.gever.goa.book.dao.impl;

import java.util.*;
import com.gever.exception.DefaultException;
import com.gever.jdbc.sqlhelper.SQLHelper;
import com.gever.jdbc.sqlhelper.DefaultSQLHelper;
import com.gever.goa.base.BaseDAO;
import com.gever.util.StringUtils;
import com.gever.vo.VOInterface;

import com.gever.goa.book.vo.BookVO;
import com.gever.goa.book.vo.BookTreeVO;
import com.gever.goa.book.dao.BookDao;

/**
 * Comment block is generated by javaClassComment.vsl
 *
 * <p>Title: </p>
 * <p>Description: Book ??</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company:OSMatrix ????</p>
 * @Author:		HuHJ
 * @Version:1.0
 *
 */
public class BookDaoImpl extends BaseDAO implements BookDao {
    private static final String QUERY_SQL = 
         "SELECT bookid,bookname,publisher,deptid from qiqu_book where 1=1 ";
    private static String TREE_SQL = 
    		     " Select id as nodeid,name as nodename,case when (Select COUNT(*) AS CNT from T_DEPARTMENT b  WHERE (T_DEPARTMENT.id>b.id or b.id>T_DEPARTMENT.id) AND b.parent_id=T_DEPARTMENT.id  ) >0 then '1' else '0' end as isfolder from T_DEPARTMENT where  1=1 ";

    public BookDaoImpl(String dbData) {
        super(dbData);
    }

    public String getPageSql() {
        return QUERY_SQL;
    }

    /**
     * @return 
     * @throws DefaultException
     */
    public List getTreeData()throws DefaultException{
        List treeData = new ArrayList();
        BookTreeVO vo = new BookTreeVO();
        SQLHelper helper = helper = new DefaultSQLHelper(dbData); ;
        treeData = (ArrayList) helper.queryByListVo(TREE_SQL, vo);
        return treeData;
    }

	    //				获取nodeid的子节点，当nodeid为空时默认为顶级节点
    public List getTreeData(String nodeid) throws DefaultException {
        System.out.println("----------getTreeDate In Impl-----------------");
        List treeData = new ArrayList();
        String strWhere = "";
        //nodeid为null，当成顶级的节点
        if ( StringUtils.isNull(nodeid)) { 		nodeid = "0"; } 

        strWhere = " and parent_id =" + nodeid; 
        BookTreeVO vo = new BookTreeVO();
        SQLHelper helper = helper = new DefaultSQLHelper(dbData);
        treeData = (ArrayList) helper.queryByListVo(TREE_SQL + strWhere, vo);
        return treeData;
    }
        
  public int insert(VOInterface vo) throws DefaultException {
    SQLHelper helper = new DefaultSQLHelper(dbData);
    helper.setAutoID(false);
    if (isRepeat( (BookVO) vo)) {
      throw new DefaultException("PK repeat!");
    }
    else {
      int iRet = helper.insert(vo);
      return iRet;
    }
  }

  private boolean isRepeat(com.gever.goa.book.vo.BookVO vo) throws
      DefaultException {
    String sql = QUERY_SQL + " and bookid = "+ vo.getValue("bookid") ;
    SQLHelper helper = new DefaultSQLHelper(dbData); ;
    boolean bRet = false;
    Map map = (HashMap) helper.query(sql,com.gever.jdbc.sqlhelper.DataTypes.RS_SINGLE_MAP);
    if (com.gever.util.NumberUtil.stringToLong( (String) map.get("cnt")) > 0) {
      bRet = true;

    }
    return bRet;

  }    
}